#:schema node_modules/wrangler/config-schema.json
name = "x-auth-test"
main = "src/index.ts"
compatibility_date = "2024-10-22"

node_compat = true
workers_dev = true

[observability]
enabled = true

# optional. default = 1.
head_sampling_rate = 1

[[workflows]]
# name of your workflow
name = "x-auth-test"

# binding name env
binding = "X_AUTH_TEST"

# this is class that extends the Workflow class in src/index.ts
class_name = "XAuthTest"

browser = { binding = "BROWSER", type = "browser" }
